version: "3.8"

services:
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile.debug
    container_name: api-gateway-debug
    ports:
      - "5000:5000"
      - "5005:5005" # Debug port
    environment:
      - SERVER_PORT=5000
      - EUREKA_URL=${EUREKA_URL:-http://eureka-server:8761/eureka}
      - JWT_SECRET=${JWT_SECRET:-ajkdfnsdkjfkjefnwejfenwjfnewlekndjwenejfnejknejnfewjfnefnewjfwenkfjew}
    networks:
      - quickhammer-network

networks:
  quickhammer-network:
    external: true
    name: quickhammer_quickhammer-network
