spring.application.name=payment-service

stripe.stripe-secret-key=sk_test_51S02L8Rp0kx0D36kxF3M6FFZDNboXZmW7kbtVdROdfAieN8yPSvBKp5NNHlonRsej7jaHDfL88Jlmn4RBwd5Itb600bqyXX9dq
payment.frontend-url=http://localhost:3000
payment.webhook-secret=whsec_XXXXXXXX

# PostgreSQL datasource
spring.datasource.url=jdbc:postgresql://localhost:5436/notificationdb
spring.datasource.username=postgres
spring.datasource.password=secret
spring.datasource.driver-class-name=org.postgresql.Driver