spring.application.name=payment-service

stripe.stripe-secret-key=${STRIPE_SECRET_KEY:sk_test_XXXXXXXX}
payment.frontend-url=${PAYMENT_FRONTEND_URL:http://localhost:3000}
payment.webhook-secret=${STRIPE_WEBHOOK_SECRET:whsec_XXXXXXXX}

# PostgreSQL datasource
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/paymentdb}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:secret}
spring.datasource.driver-class-name=org.postgresql.Driver

server.port=${SERVER_PORT:8084}

eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka}

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true

management.endpoints.web.exposure.include=*
